### ISSUE TITLE
How to make use of GPU's for this implementation

### ISSUE THREAD

**Issue by biswasaveek** [jiexunsee/Simple-Inception-Transfer-Learning#5]
Hi @jiexunsee ,
I need to get the image vectors of 1000000 images. So, the CPU implementation is too slow for my purpose. I am just starting to dig into how to make use of GPU's for this same code. 
It will be  very helpful if you could provide some insight for that.
Thanks in advance.

**Comment by jiexunsee** [comment]
hi @biswasaveek ,

yes this code takes very long to produce the image vectors, which is why I made another repository [here](https://github.com/jiexunsee/New-Simple-Inception-Transfer-Learning). You can use the producebottlenecks.py script from that repo to get your image vectors fast.

As for GPUs, as long as you have a GPU version of tensorflow installed, you'll be able to run the code using your GPU.

**Comment by biswasaveek** [comment]
Okay thanks @jiexunsee [That](https://github.com/jiexunsee/New-Simple-Inception-Transfer-Learning) works 10x faster than this to give the image vectors. But, the image vector generated for a image in this method and the one you gave reference to is different. Is it supposed to be like that?

**Comment by jiexunsee** [comment]
Yeahh I think the one here is using a different version of the inception model, so the results would be a little different
